keys:
  - &host_aladdin age147qz8tf8tlctz78l4kmgruu032z9jd9v4wku3slpx0m2fek7effqn2tv9u
  - &host_mahdi age1k6hkw62h3js987u666pj4y2ld3p8yvd38e8w8z3sgfc3tflyjq9sru0mf7

  - &admin_kg_aladdin age1860xuy8hczqepjr5ys9mm6nshtdkss98uv0pj64d9xy4tyct8gkq4c87gl
  - &admin_kg_mahdi age16xq27lvvv3j7pvkp0rk6jzljdhldevlrucnv906tuq0mfecvuq4q0pznww

creation_rules:
  - path_regex: modules\/hosts\/aladdin\/secrets\.yaml$
    key_groups:
      - age:
          - *host_aladdin
          - *admin_kg_aladdin

  - path_regex: modules\/hosts\/mahdi\/secrets\.yaml$
    key_groups:
      - age:
          - *host_mahdi
          - *admin_kg_mahdi
          # TODO: There must be a better way... Right?
          # This is done for when access to "mahdi" is lost
          - *admin_kg_aladdin

  - path_regex: modules\/users\/kg\/secrets\.yaml$
    key_groups:
      - age:
          - *host_aladdin
          - *host_mahdi
          - *admin_kg_aladdin
          - *admin_kg_mahdi
