# TODO: Generate this file with the files project
keys:
  - &admin_kg_aladdin age18rg3styd6qwn7ufx0e2suv9pa5g6236y05c2vpgc7cxuk5ug73msq9dtnd
  - &admin_kg_mahdi age16xq27lvvv3j7pvkp0rk6jzljdhldevlrucnv906tuq0mfecvuq4q0pznww
  - &admin_kg_sindbad age1dgxc76ehxl0dygcrgh7kyqwfe6wyjx3m5wqj8pm5vt37c4j96g8qhle37c

  - &host_aladdin age19cc3n0sl50wgn7wzy2zs89l7x7fqxgf3n3jrsyx6s5k9v3ugl9mqyhhslr
  - &host_mahdi age1k6hkw62h3js987u666pj4y2ld3p8yvd38e8w8z3sgfc3tflyjq9sru0mf7
  - &host_morgiana age1qqlwzz2cpk5khpdsg28euquv0utnh6725g8acg5wtcfa8gj7n3aqu78fn0
  - &host_sheherazade age146xt2y57kw2n3ccrs9fltspka257e2v46zs7w98p7t4vej7clupqzuldmk
  - &host_zarqa age1kdde6nslzke8u5mqey2mra7h85vdh5gtjz52qygwfd6pgdux5qjqak6euc

creation_rules:
  - path_regex: secrets\/.+\.yaml$
    key_groups:
      - age:
          - *admin_kg_aladdin
          - *admin_kg_mahdi
          - *admin_kg_sindbad

          - *host_aladdin
          - *host_mahdi
          - *host_morgiana
          - *host_sheherazade
          - *host_zarqa

  - path_regex: modules\/hosts\/sheherazade\/secrets\.yaml$
    key_groups:
      - age:
          - *host_sheherazade
          - *admin_kg_aladdin
          - *admin_kg_mahdi
          - *admin_kg_sindbad

  - path_regex: modules\/hosts\/mahdi\/secrets\.yaml$
    key_groups:
      - age:
          - *host_mahdi
          - *admin_kg_aladdin
          - *admin_kg_mahdi
          - *admin_kg_sindbad

  - path_regex: modules\/hosts\/morgiana\/secrets\.yaml$
    key_groups:
      - age:
          - *host_morgiana
          - *admin_kg_aladdin
          - *admin_kg_mahdi
          - *admin_kg_sindbad

  - path_regex: modules\/users\/kg\/secrets\.yaml$
    key_groups:
      - age:
          - *host_aladdin
          - *host_mahdi
          - *host_morgiana
          - *host_sheherazade
          - *host_zarqa
          - *admin_kg_aladdin
          - *admin_kg_mahdi
          - *admin_kg_sindbad
