keys:
  - &host_aladdin age147qz8tf8tlctz78l4kmgruu032z9jd9v4wku3slpx0m2fek7effqn2tv9u
  - &admin_kg age1hft9v6r9zpa23pxhamuhm9tnmvx39m56chfn8t996wn8v4txts2s3jjpwa

creation_rules:
  - path_regex: modules\/hosts\/aladdin\/secrets\.yaml$
    key_groups:
      - age:
          - *host_aladdin
          - *admin_kg
  - path_regex: modules\/users\/kg\/secrets\.yaml$
    key_groups:
      - age:
          - *host_aladdin
          - *admin_kg
