keys:
  - &kg age1aq8u2tm6v5ylvjn5g5hzysnxf9tlsrkgl4s3ykkhu30nf0ce6u9sn9vspu
  - &tp age1vy2rjgm67w96m3tkl4zgkhqudld9r6nnr55yuu287c4d9rt7x95stqrvlx
creation_rules:
  - path_regex: hosts\/.+\/aladdin\/secrets\.yaml$
    key_groups:
      - age:
          - *kg
  - path_regex: hosts\/.+\/aladdin\/users\/kg\/secrets\.yaml$
    key_groups:
      - age:
          - *kg

  - path_regex: hosts\/.+\/sindbad\/secrets\.yaml$
    key_groups:
      - age:
          - *tp
  - path_regex: hosts\/.+\/sindbad\/users\/tp\/secrets\.yaml$
    key_groups:
      - age:
          - *tp
