[default.extend-words]
noice = "noice"
facter = "facter"
nitch = "nitch"

[files]
extend-exclude = [
  "modules/hosts/*/facter.json",
  "modules/hosts/*/secrets.yaml",
  "modules/users/*/secrets.yaml"
]
