{
  imports = [
    ./starship

    ./atuin.nix
    ./bacon.nix
    ./bandwhich.nix
    ./bash.nix
    ./bat.nix
    ./broot.nix
    ./btop.nix
    ./cava.nix
    ./dconf.nix
    ./direnv.nix
    ./fastfetch.nix
    ./fd.nix
    ./fzf.nix
    ./git-cliff.nix
    ./git.nix
    ./gitui.nix
    ./kitty.nix
    ./lsd.nix
    ./navi.nix
    ./nix-index.nix
    ./nushell.nix
    ./packages.nix
    ./ripgrep.nix
    ./tealdeer.nix
    ./thefuck.nix
    ./yazi.nix
    ./zellij.nix
    ./zoxide.nix
  ];
}
