name: CI Check flake

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@78d714f6f717f43be9f3f5b867a2ce6ab84db093

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@b33274111e3a8c70e8845fe1a4605911a70486f7
        with:
          fail-mode: true
          send-statistics: false

      # Fails due to nix-invisible being required...
      # TODO: workaround this issue
      # - name: Check flake
      #   run: nix flake check --extra-experimental-features pipe-operators
