name: CI Check flake

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@37dc9ba6c4bd58da00a2f31c3c546eb5cb71045e

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@5a8af4d80499eeee8cdd2012c4ef25a629a01a4f
        with:
          fail-mode: true
          send-statistics: false

      # Fails due to nix-invisible being required...
      # TODO: workaround this issue
      # - name: Check flake
      #   run: nix flake check --extra-experimental-features pipe-operators
