name: CI Check flake

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@c723f3a885e3f1d866d91f4f0c33dd44b1fc7c60

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@0af51e37404acfb298f7e2eec77470be27eb57c5
        with:
          fail-mode: true
          send-statistics: false

      # Fails due to nix-invisible being required...
      # TODO: workaround this issue
      # - name: Check flake
      #   run: nix flake check --extra-experimental-features pipe-operators
