name: CI Check flake

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@7239c695c3bf911d23a9cb41013aff459f808c8c

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@35dffcac44d3e8a11bda64dd5d37ddc3afa52c08
        with:
          fail-mode: true
          send-statistics: false

      # Fails due to nix-invisible being required...
      # TODO: workaround this issue
      # - name: Check flake
      #   run: nix flake check --extra-experimental-features pipe-operators
