name: CI Check flake

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@8f9243d6dde967b53cc73719b9b6284c5102e543

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@f571e072c06a69a1a77afd81ed761b817be8bb79
        with:
          fail-mode: true
          send-statistics: false

      # Fails due to nix-invisible being required...
      # TODO: workaround this issue
      # - name: Check flake
      #   run: nix flake check --extra-experimental-features pipe-operators
