name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

permissions: {}

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write # required for peter-evans/create-issue-from-file
    steps:
      - uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb
        with:
          persist-credentials: false
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@f613c4a64e50d792e0b31ec34bbcbba12263c6a6
        with:
          fail: false
          args: --header "accept=*/*" ./*.md ./*.nix ./hosts/**/*.nix

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@5bf5cf922b10209b1542342c097efcf0d2ecbced
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
